### ISSUE TITLE
Error while testing with custom images

### ISSUE THREAD

**Issue by karthik1997** [minar09/cp-vton-plus#27]
I really appreciate your work. 

i am getting an error like this while testing custom images,

return F.conv2d(input, weight, self.bias, self.stride,                                                              
RuntimeError: Given groups=1, weight of size [64, 22, 4, 4], expected input[3, 28, 256, 192] to have 22 channels, but got 28 channels instead

**Comment by minar09** [comment]
Hi @karthik1997 , looks like you have input mismatch. Please read the readme file for testing custom images and try accordingly. If the error still persists, then please comment with your inputs with their channels/dimensions.

**Comment by karthik1997** [comment]
The inputs are according to the instructions. I am sharing the images here:
![000118_1](https://user-images.githubusercontent.com/33384466/94008217-42885300-fdc0-11ea-8a5c-2d99e8ea0c45.jpg)
![000118_1](https://user-images.githubusercontent.com/33384466/94008245-516f0580-fdc0-11ea-821d-0e58a6b7784e.jpg)
![abc](https://user-images.githubusercontent.com/33384466/94008258-58961380-fdc0-11ea-9299-6e525fde13b3.jpg)
![abc](https://user-images.githubusercontent.com/33384466/94008278-5fbd2180-fdc0-11ea-99d6-75a9f53b6ed7.png)
![abc](https://user-images.githubusercontent.com/33384466/94008294-66e42f80-fdc0-11ea-929a-83209563d0b6.png)

**Comment by karthik1997** [comment]
> The inputs are according to the instructions. I am sharing the images here:
> ![000118_1](https://user-images.githubusercontent.com/33384466/94008217-42885300-fdc0-11ea-8a5c-2d99e8ea0c45.jpg)
> ![000118_1](https://user-images.githubusercontent.com/33384466/94008245-516f0580-fdc0-11ea-821d-0e58a6b7784e.jpg)
> ![abc](https://user-images.githubusercontent.com/33384466/94008258-58961380-fdc0-11ea-9299-6e525fde13b3.jpg)
> ![abc](https://user-images.githubusercontent.com/33384466/94008278-5fbd2180-fdc0-11ea-99d6-75a9f53b6ed7.png)
> ![abc](https://user-images.githubusercontent.com/33384466/94008294-66e42f80-fdc0-11ea-929a-83209563d0b6.png)
> 
> 

@minar09

**Comment by minar09** [comment]
Hi @karthik1997 , its very difficult to understand the issue just by looking at the images. Your input images seem okay, but I don't know their input channels. Please check the inputs with their dimensions. For example, segmentation input will be the [0,20] grayscale input, not like the one showed here (RGB). I think you can find the origin of the issue with a little debugging. Good luck.

**Comment by minar09** [comment]
If its still giving error, you can comment here with the full error traceback. That way it will be easier to understand. Thank you.

**Comment by karthik1997** [comment]
Let me see @minar09

**Comment by karthik1997** [comment]
@minar09 I used graphonomy for segmentation , will that be an issue? The input image is RGB and output image is the segmentation image which I posted. Converted that 24bit image into 8 bit according to the prerequisite.

**Comment by minar09** [comment]
What is the label numbers of Graphonomy? Please check if its similar to LIP/PGN. 
Also, there should be a generated grayscale [0,20] output segmentation file, you don't need to convert from RGB. See the difference below or check the VITON dataset segmentation files.

![000038_0](https://user-images.githubusercontent.com/3684134/94098826-7d43c700-fe64-11ea-9573-565c6c04defe.png)
![000038_0_vis](https://user-images.githubusercontent.com/3684134/94098840-8339a800-fe64-11ea-80c6-4df166e8b87b.png)

**Comment by karthik1997** [comment]
@minar09 
hi ,
Thank you for the help.
I tried with them also adding the images here:
![abc](https://user-images.githubusercontent.com/33384466/94145518-4be0f080-fe90-11ea-9a9e-cade374dee83.png)
![abc](https://user-images.githubusercontent.com/33384466/94145534-526f6800-fe90-11ea-9b70-e503c7ccfce6.png)

attaching the entire traceback here:

Traceback (most recent call last):                                                                                                                                                                                   File "test.py", line 225, in <module>                                                                                                                                                                                main()                                                                                                                                                                                                           File "test.py", line 211, in main                                                                                                                                                                                    test_gmm(opt, test_loader, model, board)                                                                                                                                                                         File "test.py", line 99, in test_gmm                                                                                                                                                                                 grid, theta = model(agnostic, cm)                                                                                                                                                                                File "C:\Users\Karthik\anaconda3\envs\torch_gpu\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl                                                                                               result = self.forward(*input, **kwargs)                                                                                                                                                                          File "C:\Users\Karthik\cp-vton-plus-master\networks.py", line 518, in forward                                                                                                                                        featureA = self.extractionA(inputA)                                                                                                                                                                              File "C:\Users\Karthik\anaconda3\envs\torch_gpu\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl                                                                                               result = self.forward(*input, **kwargs)                                                                                                                                                                          File "C:\Users\Karthik\cp-vton-plus-master\networks.py", line 79, in forward                                                                                                                                         return self.model(x)                                                                                                                                                                                             File "C:\Users\Karthik\anaconda3\envs\torch_gpu\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl                                                                                               result = self.forward(*input, **kwargs)                                                                                                                                                                          File "C:\Users\Karthik\anaconda3\envs\torch_gpu\lib\site-packages\torch\nn\modules\container.py", line 117, in forward                                                                                               input = module(input)                                                                                                                                                                                            File "C:\Users\Karthik\anaconda3\envs\torch_gpu\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl                                                                                               result = self.forward(*input, **kwargs)                                                                                                                                                                          File "C:\Users\Karthik\anaconda3\envs\torch_gpu\lib\site-packages\torch\nn\modules\conv.py", line 419, in forward                                                                                                    return self._conv_forward(input, self.weight)                                                                                                                                                                    File "C:\Users\Karthik\anaconda3\envs\torch_gpu\lib\site-packages\torch\nn\modules\conv.py", line 415, in _conv_forward                                                                                              return F.conv2d(input, weight, self.bias, self.stride,                                                                                                                                                         RuntimeError: Given groups=1, weight of size [64, 22, 4, 4], expected input[1, 28, 256, 192] to have 22 channels, but got 28 channels instead

**Comment by thaithanhtuan** [comment]
Based on the traceback, the error comes from the size of agnostic. It should be 22 channels. But the agnostic of your custom image return 28 channels.
You can check the size of these data:
![image](https://user-images.githubusercontent.com/19486377/94166318-2078f880-fec6-11ea-953c-4b8ffbeb38e9.png)
by debugging cp_dataset.py  line 178. (print out the shape of these inputs)
Check: shape: 1 channel; im_h: 3 channels; pose_map: 18 channels. Maybe one of your inputs got the wrong size.
Regards.

**Comment by karthik1997** [comment]
@thaithanhtuan  @minar09 ,

I found the error. I am getting the shape of pose_map as 24 instead of 18. How can i solve this issue?

**Comment by karthik1997** [comment]
@thaithanhtuan  @minar09 ,

i used the openpose pytorch implementation for generating the keypoints.

https://github.com/minar09/openpose-pytorch

**Comment by minar09** [comment]
@karthik1997 , use the coco-18 model from the original openpose repository.

**Comment by karthik1997** [comment]
Ok Minar,

Thank you. Will try that out and post the try on results here. 

One more question... Is it possible to try on for bottomwears also with this algorithm?

**Comment by minar09** [comment]
for different apparel than upper cloth, you can follow a similar procedure. You may need datasets and training separate models for that.

**Comment by karthik1997** [comment]
@minar09 ,  Thank you, so try on for bottomwear and topwear is not possible with this algorithm even if we can get the data for training the same? do we have to go for a different approach?

**Comment by minar09** [comment]
@karthik1997 , not sure. This is an active research area with many challenges. You can explore the latest various research works or try your own approach.

**Comment by thaithanhtuan** [comment]
@karthik1997 from 24 keypoints, you can check what are they and remove 6 from 24 to get 18 keypoints.
Or change input of GMM from 22 channels to 28 channels.
About bottom wear, please define the problem, what is inputs and desired ouput?

**Comment by karthik1997** [comment]
@thaithanhtuan ,

How can I generate the same output with 28 channels?

Regarding the bottomear, I've data for desired person's photo, the required topwear and required bottomwear photo. I need to try on the top and bottom wear on the desired person's image. 

If I have a good amount of data like this can I achieve the Tryon results of top and bottom wear with the same code?

**Comment by karthik1997** [comment]
@minar09 @thaithanhtuan ,

getting the same error after extracting the pose with coco-18 model

**Comment by karthik1997** [comment]
@minar09 @thaithanhtuan ,

can you provide me the actual coco-18 model file?

**Comment by karthik1997** [comment]
@minar09 @thaithanhtuan ,

can you provide me the link to actual coco-18 model file?

**Comment by minar09** [comment]
Openpose repo: https://github.com/CMU-Perceptual-Computing-Lab/openpose
How to generate joints: https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/demo_overview.md
Release: https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases/tag/v1.6.0
Download models: https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/models/getModels.bat
or https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/models/getModels.sh

**Comment by karthik1997** [comment]
Thank You
