### ISSUE TITLE
 Images with different size

### ISSUE THREAD

**Issue by SarahH20** [minar09/cp-vton-plus#32]
Hi. If I would like to train the model with images at different size (e.g. 288 x 512, which is 1.5 times the current image size (192 x 256)), can I do so? If so, do I need to change any data in the model?

Thanks for your help,

**Comment by thaithanhtuan** [comment]
You have to change the network architecture to your size. (networks.py) and also the data augmentation.
------------------------
For fast test, you can resize all input, feed into network, then resize output. 
For GMM, you can also make use of TPS params (output of regression network), then apply on full images size directly.
One problem with resize is losing information (texture) from input.

**Comment by SarahH20** [comment]
Thanks @thaithanhtuan  for your advice. I'll try to change the data in the networks.py. What do you mean by changing "data augmentation" as well? Thanks again for your help.

**Comment by thaithanhtuan** [comment]
Sorry, Im wrong. I mean this.
![image](https://user-images.githubusercontent.com/19486377/97834532-6d4cbc00-1d1b-11eb-934e-b187a40f680e.png)

**Comment by SarahH20** [comment]
Thanks @thaithanhtuan Your answer is much appreciated. As I look into the networks.py file, I found 3 places where I need to change so that images with size of 288 x 384 can work with this model. Could you help to review these changes and advise if they're correct and if there're other places in this file that I need to change? Thank you so much for your great help.
<img width="1157" alt="CPVTONPlus1" src="https://user-images.githubusercontent.com/73695076/97836730-0803c580-1d31-11eb-82a4-6d89e4ae6e15.png">
<img width="1041" alt="CPVTONPlus2" src="https://user-images.githubusercontent.com/73695076/97836746-10f49700-1d31-11eb-8ff8-7139f7d29889.png">

**Comment by thaithanhtuan** [comment]
Only change the image input size and image output size, 
On line 116, Do not change here --> this is the number of channels not image size.
If I have time, I will check all the projects, may be we also need to change other files (not only networks.py)
Regards,

**Comment by SarahH20** [comment]
Thanks @thaithanhtuan

**Comment by SarahH20** [comment]
Hi there. I just tried training GMM with images of size 384x512 and encountered this error. Do you know why this happened? Thanks for your help as always!

*********

Traceback (most recent call last):
  File "train.py", line 321, in <module>
    main()
  File "train.py", line 292, in main
    train_gmm(opt, train_loader, model)
  File "train.py", line 117, in train_gmm
    grid, refine = model(agnostic, cm, c)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/notebooks/networks.py", line 530, in forward
    theta = self.regression(correlation)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/notebooks/networks.py", line 137, in forward
    x = self.conv(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 343, in forward
    return self.conv2d_forward(input, self.weight)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 340, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 512 192 4 4, expected input[4, 768, 32, 24] to have 192 channels, but got 768 channels instead

**Comment by SarahH20** [comment]
> Hi @thaithanhtuan . I just tried training GMM with images of size 384x512 and encountered this error. Do you know why this happened? Thanks for your help as always!
> 
> Traceback (most recent call last):
> File "train.py", line 321, in
> main()
> File "train.py", line 292, in main
> train_gmm(opt, train_loader, model)
> File "train.py", line 117, in train_gmm
> grid, refine = model(agnostic, cm, c)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "/notebooks/networks.py", line 530, in forward
> theta = self.regression(correlation)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "/notebooks/networks.py", line 137, in forward
> x = self.conv(x)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 92, in forward
> input = module(input)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 343, in forward
> return self.conv2d_forward(input, self.weight)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 340, in conv2d_forward
> self.padding, self.dilation, self.groups)
> RuntimeError: Given groups=1, weight of size 512 192 4 4, expected input[4, 768, 32, 24] to have 192 channels, but got 768 channels instead

Hi there. Does anyone have any advice on how to fix this issue? Many thanks,

**Comment by thaithanhtuan** [comment]
![image](https://user-images.githubusercontent.com/19486377/98902823-c544a900-24f9-11eb-8331-74f7c817a94b.png)
The in put for the regression is based on  the output of correlation.
Please check by printing out the correlation variable in
![image](https://user-images.githubusercontent.com/19486377/98903132-5156d080-24fa-11eb-9b7b-ba1ca8ea7e28.png)
Then, change the input_nc in line 513 to that number
![image](https://user-images.githubusercontent.com/19486377/98903210-7ea37e80-24fa-11eb-9534-0c75763d5133.png)

PS: May be in your case, it is 768.

**Comment by SarahH20** [comment]
Many thanks. I tried to use 768 for this but faced another error with size mismatch. Any advice on how to fix this? 

<img width="937" alt="Screen Shot 2020-11-12 at 7 40 19 pm" src="https://user-images.githubusercontent.com/73695076/98916263-0e5b2400-251f-11eb-8a65-b4278b9f433f.png">

**Comment by thaithanhtuan** [comment]
![image](https://user-images.githubusercontent.com/19486377/98937087-449da100-2529-11eb-8bdd-4281e0376c2c.png)
At A position, print out the shape of x. (with normal size it is: 64 x 3 x 4 = 768, at B)
Then, change the number at B to correct number.

**Comment by SarahH20** [comment]
Many thanks

**Comment by amandazw** [comment]
Hi
I use my own data with 384*512, here is the error:
RuntimeError: Given groups=1, weight of size 64 22 4 4, expected input[4, 29, 512, 384] to have 22 channels, but got 29 channels instead
could you help? thanks a lot

**Comment by omaraga12** [comment]
> ![image](https://user-images.githubusercontent.com/19486377/98937087-449da100-2529-11eb-8bdd-4281e0376c2c.png) At A position, print out the shape of x. (with normal size it is: 64 x 3 x 4 = 768, at B) Then, change the number at B to correct number.

Hello, thank you for this great job. I am trying to train with 1024x768 images, I followed all the steps, but at the finall I got this error:
![image](https://user-images.githubusercontent.com/64969223/167062981-8091b55d-efc3-4687-a4b0-84945b08dc8d.png)
The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0
Can you guide me to resolve it please. thank you so much
