### ISSUE TITLE
output with shape [1, 256, 192] doesn't match the broadcast shape [3, 256, 192]

### ISSUE THREAD

**Issue by j-sieger** [minar09/cp-vton-plus#6]
File "test.py", line 224, in <module>
    main()
  File "test.py", line 210, in main
    test_gmm(opt, test_loader, model, board)
  File "test.py", line 83, in test_gmm
    for step, inputs in enumerate(test_loader.data_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/My Drive/Colab Notebooks/VirtualTryOn/cp-vton-plus/cp_dataset.py", line 140, in __getitem__
    shape_ori = self.transform(parse_shape_ori)  # [-1,1]
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 166, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean).div_(std)
RuntimeError: output with shape [1, 256, 192] doesn't match the broadcast shape [3, 256, 192]

**Comment by minar09** [comment]
Hi @j-sieger , I think this issue was solved before in the previous issues. Please use the updated code and the correct checkpoints from the readme file. And also our code will run in PyTorch==0.4.1

**Comment by j-sieger** [comment]
instead of degrading the pytorch version. i have modified the transform fuction to output 1 channel instead of 3 channels. 
transforms.Normalize((0.5), (0.5))

**Comment by JahangirButt-BU** [comment]
> instead of degrading the pytorch version. i have modified the transform fuction to output 1 channel instead of 3 channels.
> transforms.Normalize((0.5), (0.5))

can I know what exactly and where exactly you made changes I'm also facing this error.

**Comment by amrahsmaytas** [comment]
> > instead of degrading the pytorch version. i have modified the transform fuction to output 1 channel instead of 3 channels.
> > transforms.Normalize((0.5), (0.5))
> 
> can I know what exactly and where exactly you made changes I'm also facing this error.

@JahangirButt-BU Hey, did you find out any solution for it?

**Comment by amrahsmaytas** [comment]
@minar09 could you guide me or point to any resource,to know whats the modifications need to done, to use latest version of the pytorch!

Thanks!

**Comment by thaithanhtuan** [comment]
![image](https://user-images.githubusercontent.com/19486377/99247788-c869cd00-284a-11eb-8b69-64059e14834b.png)
IN cp_dataset.py
@amrahsmaytas

**Comment by amrahsmaytas** [comment]
> ![image](https://user-images.githubusercontent.com/19486377/99247788-c869cd00-284a-11eb-8b69-64059e14834b.png)
> IN cp_dataset.py
> @amrahsmaytas 

Tried replacing **transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])**  with **transforms.Normalize((0.5, 0.5), (0.5, 0.5))])**

But, i am getting an error 
RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

AM i doing something wrong,whats LOC for replacement?

**Comment by thaithanhtuan** [comment]
![image](https://user-images.githubusercontent.com/19486377/99342820-052bd780-28d0-11eb-8c0b-682f156afcec.png)
Replace with above.

**Comment by amrahsmaytas** [comment]
> ![image](https://user-images.githubusercontent.com/19486377/99342820-052bd780-28d0-11eb-8c0b-682f156afcec.png)
> Replace with above.

Thanks @thaithanhtuan for LOC

**Comment by amrahsmaytas** [comment]
**update**

############################### FOR TORCH DEPENDENCY UPGRADE #######################

# make changes in cp_dataset , in line 32 to
`transforms.Normalize((0.5,), (0.5,))])`
# make changes in networks.py, in  line 135 to  
 `x = x.reshape(x.size(0), -1)`

**ABLE TO RUN SUCCESSFULLY FOR FOLLOWING TORCH,TORCHVISION VERSION'S**
Torch version: 1.7.0+cu101 
Torch vision Version: 0.8.1+cu101
