### ISSUE TITLE
size issue when running train.py GMM

### ISSUE THREAD

**Issue by joel1895** [minar09/cp-vton-plus#7]
### I have been trying solve it but didnt reach anywhere. The output shape is not able to match the broadcast shape

python train.py --name GMM --stage GMM --workers 4 --save_count 5000 --shuffle

Namespace(batch_size=4, checkpoint='', checkpoint_dir='checkpoints', data_list='train_pairs.txt', datamode='train', dataroot='data', decay_step=100000, display_count=20, fine_height=256, fine_width=192, gpu_ids='', grid_size=5, keep_step=100000, lr=0.0001, name='GMM', radius=5, save_count=5000, shuffle=True, stage='GMM', tensorboard_dir='tensorboard', workers=4)
Start to train stage: GMM, named: GMM!
initialization method [normal]
initialization method [normal]
Traceback (most recent call last):
  File "train.py", line 229, in <module>
    main()
  File "train.py", line 210, in main
    train_gmm(opt, train_loader, model, board)
  File "train.py", line 72, in train_gmm
    inputs = train_loader.next_batch()
  File "/content/gdrive/My Drive/virtual mirror/cp_dataset.py", line 228, in next_batch
    batch = self.data_iter.__next__()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/gdrive/My Drive/virtual mirror/cp_dataset.py", line 138, in __getitem__
    shape_ori = self.transform(parse_shape_ori)  # [-1,1]
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 166, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean).div_(std)
RuntimeError: output with shape [1, 256, 192] doesn't match the broadcast shape [3, 256, 192]

**Comment by minar09** [comment]
I think you are running with a different pytorch version. We tested on pytorch 0.4.1 and torchvision 0.2.1. If you are using pytorch < 1.0, you need to update the transform function in cp_dataset.py file.

**Comment by minar09** [comment]
https://github.com/minar09/cp-vton-plus/issues/6

**Comment by minar09** [comment]
#6

**Comment by joel1895** [comment]
okay thank you soo much, it was the version difference! the training has begun. I dont know why I faced it even though I ran requirements.txt file

**Comment by minar09** [comment]
Great, you are welcome! Glad to help.
